# Generated by Django 4.2.7 on 2025-12-15 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_user_type_remove_user_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('role_title', models.CharField(help_text='Job title (e.g., Senior Dentist, Nurse)', max_length=100)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('mfa_secret', models.CharField(blank=True, max_length=100, null=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Admin approval required')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_staff', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
                'db_table': 'staff_profiles',
            },
        ),
        migrations.CreateModel(
            name='StaffAuthorizationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('employee_id', models.CharField(max_length=20)),
                ('registration_code', models.CharField(max_length=50)),
                ('success', models.BooleanField(default=False)),
                ('attempt_count', models.IntegerField(default=1)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Staff Authorization Attempt',
                'verbose_name_plural': 'Staff Authorization Attempts',
                'db_table': 'staff_authorization_attempts',
                'indexes': [models.Index(fields=['ip_address', 'created_at'], name='staff_autho_ip_addr_822384_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegistrationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_type', models.CharField(choices=[('PATIENT', 'Patient'), ('STAFF', 'Staff')], max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registration Attempt',
                'verbose_name_plural': 'Registration Attempts',
                'db_table': 'registration_attempts',
                'indexes': [models.Index(fields=['ip_address', 'created_at'], name='registratio_ip_addr_b76a34_idx'), models.Index(fields=['user_type', 'created_at'], name='registratio_user_ty_d19b4e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('medical_conditions', models.TextField(blank=True, help_text='List any medical conditions', null=True)),
                ('allergies', models.TextField(blank=True, help_text='List any allergies', null=True)),
                ('current_medications', models.TextField(blank=True, help_text='Current medications', null=True)),
                ('dental_history', models.TextField(blank=True, help_text='Previous dental treatments', null=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_number', models.CharField(blank=True, max_length=50, null=True)),
                ('consent_treatment', models.BooleanField(default=False)),
                ('consent_data_sharing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Profile',
                'verbose_name_plural': 'Patient Profiles',
                'db_table': 'patient_profiles',
            },
        ),
    ]
