# Generated by Django 4.2.7 on 2025-12-14 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_branch_doctorprofile_branch_doctorschedule'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='accounts.branch'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ATTENDED', 'Attended'), ('MISSED', 'Missed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='UPCOMING', max_length=10),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'appointment_date'], name='appointment_patient_ee8848_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'appointment_date'], name='appointment_doctor__4449b5_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['branch', 'appointment_date'], name='appointment_branch__e491c9_idx'),
        ),
    ]
